name: "Submit Provenance"
description: "Submits SLSA Provenance to Ensignia Control-Plane"
inputs:
  api-key:
    description: "Ensignia API Key for GitHub Actions"
    required: true
  provenance-name:
    description: "The SLSA Release Attestation .intoto.jsonl file"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"

  # using: "composite"
  # steps:
  #   - name: Download artifact
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: ${{needs.build.outputs.go-provenance-name}}
  #   - name: Upload provenance
  #     # uses: actions/heroku@1.0.0
  #     uses: "docker"
  #     image: "Dockerfile"

  #   - run: echo Hello ${{ inputs.who-to-greet }}.
  #     shell: bash
  #   - id: random-number-generator
  #     run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
  #     shell: bash
  #   - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
  #     shell: bash
  #   - run: goodbye.sh
  #     shell: bash
